<a href="https://colab.research.google.com/github/techbala1590/weekly-task/blob/main/Task_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

In [ ]:
drive.mount( '/content/drive' )

Mounted at /content/drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# 1. Loading a CSV File & Basic Exploration
# Given a CSV file named "Automobile.csv":
# Task
# Write Python code to:
# Load the CSV file into a Pandas DataFrame.
# •	Display the first 30 rows.
# •	Print column names.
# •	Print No of Rows & Columns
# •	Find the Data Types of every column & check if there are any mismatch
# •	What are the minimum & maximum price of the car & state fuel type they belong to
# •	List all the unique engine types
# •	Find the horsepower range
# •	What is the average mpg in cities & highway. Which is better?
# •	What are the different Automobile makes present & which has maximum count?
from enum import auto
import pandas as pd
automobile = pd.read_csv('/content/drive/MyDrive/data/Automobile.csv')
automobile.head(30)



symboling  normalized_losses         make fuel_type aspiration  \
0           3                168  alfa-romero       gas        std   
1           3                168  alfa-romero       gas        std   
2           1                168  alfa-romero       gas        std   
3           2                164         audi       gas        std   
4           2                164         audi       gas        std   
5           2                161         audi       gas        std   
6           1                158         audi       gas        std   
7           1                168         audi       gas        std   
8           1                158         audi       gas      turbo   
9           2                192          bmw       gas        std   
10          0                192          bmw       gas        std   
11          0                188          bmw       gas        std   
12          0                188          bmw       gas        std   
13          1                149          bmw       gas        std   
14          0                149          bmw       gas        std   
15          0                149          bmw       gas        std   
16          0                149          bmw       gas        std   
17          2                121    chevrolet       gas        std   
18          1                 98    chevrolet       gas        std   
19          0                 81    chevrolet       gas        std   
20          1                118        dodge       gas        std   
21          1                118        dodge       gas        std   
22          1                118        dodge       gas      turbo   
23          1                148        dodge       gas        std   
24          1                148        dodge       gas        std   
25          1                148        dodge       gas        std   
26          1                148        dodge       gas      turbo   
27         -1                110        dodge       gas        std   
28          3                145        dodge       gas      turbo   
29          2                137        honda       gas        std   

   number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0              two  convertible          rwd           front        88.6  ...   
1              two  convertible          rwd           front        88.6  ...   
2              two    hatchback          rwd           front        94.5  ...   
3             four        sedan          fwd           front        99.8  ...   
4             four        sedan          4wd           front        99.4  ...   
5              two        sedan          fwd           front        99.8  ...   
6             four        sedan          fwd           front       105.8  ...   
7             four        wagon          fwd           front       105.8  ...   
8             four        sedan          fwd           front       105.8  ...   
9              two        sedan          rwd           front       101.2  ...   
10            four        sedan          rwd           front       101.2  ...   
11             two        sedan          rwd           front       101.2  ...   
12            four        sedan          rwd           front       101.2  ...   
13            four        sedan          rwd           front       103.5  ...   
14            four        sedan          rwd           front       103.5  ...   
15             two        sedan          rwd           front       103.5  ...   
16            four        sedan          rwd           front       110.0  ...   
17             two    hatchback          fwd           front        88.4  ...   
18             two    hatchback          fwd           front        94.5  ...   
19            four        sedan          fwd           front        94.5  ...   
20             two    hatchback          fwd           front        93.7  ...   
21             two    hatchback          fwd       

In [ ]:
# 2. Accessing Data with .loc[]
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Name": ["Alice", "Bob", "Charlie", "David"],
#     "Age": [24, 27, 22, 32],
#     "Score": [85, 90, 78, 88]
# })
# Task
# •	Retrieve the row where Name == "Charlie" using .loc[].
# •	Select only the Age and Score columns for "Alice" and "Bob" using .loc[].
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Name": ["Alice", "Bob", "Charlie", "David"],
     "Age": [24, 27, 22, 32],
     "Score": [85, 90, 78, 88]
})
#print(df)
print(df.loc[df["Name"]=="David"])
#print(df.loc[df["Name"].isin(["Alice", "Bob"]), ["Age", "Score"]])


    Name  Age  Score
3  David   32     88


In [ ]:
# 3. Accessing Data with .iloc[]
# Using the same DataFrame from Question 2, write code to:
# •	Retrieve the second row using .iloc[].
# •	Extract the last two rows using .iloc[].
# ________________________________________
import pandas as pd
cc = pd.DataFrame({
     "Name": ["Alice", "Bob", "Charlie", "David"],
     "Age": [24, 27, 22, 32],
     "Score": [85, 90, 78, 88]
})
print(len(cc))
#print(cc)
print(df.iloc[1])
print(df.iloc[-2:])

4
Name     Bob
Age       27
Score     90
Name: 1, dtype: object
      Name  Age  Score
2  Charlie   22     78
3    David   32     88


In [ ]:
# 4. Filtering Rows Based on Conditions
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Employee": ["John", "Alice", "Bob", "David"],
#     "Salary": [50000, 60000, 55000, 65000],
#     "Department": ["IT", "HR", "IT", "Finance"]
# })
# Task
# Write a Pandas command to:
# •	Select only IT employees.
# •	Select employees with a salary greater than 55,000.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Employee": ["John", "Alice", "Bob", "David"],
     "Salary": [50000, 60000, 55000, 65000],
     "Department": ["IT", "HR", "IT", "Finance"]
 })
print(df.loc[df["Department"] == "IT"])
#df.loc[df["Salary"]>55000]
#print(df[df["Department"]== "IT"])
#print(df[df["Salary"]>55000])

  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT


In [ ]:
# 5. Applying Functions to a Column
# Using the following DataFrame:
# df = pd.DataFrame({
#     "Student": ["A", "B", "C", "D"],
#     "Marks": [45, 78, 62, 90]
# })
# Task
# Write a function that:
# •	Converts marks below 50 to "Fail", and 50 or above to "Pass".
# •	Apply this function to the "Marks" column and create a new column "Result".
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Student": ["A", "B", "C", "D"],
     "Marks": [45, 78, 62, 90]
 })
df.loc[df["Marks"] >= 50, "R"] = "Pass"
df.loc[df["Marks"] < 50, "R"] = "Fail"
print(df)

  Student  Marks     R
0       A     45  Fail
1       B     78  Pass
2       C     62  Pass
3       D     90  Pass


In [ ]:
# 6. NumPy - Creating and Reshaping Arrays
# Write Python code to:
# •	Create a NumPy array with values from 1 to 12.
# •	Reshape it into a 3x4 matrix.
# ________________________________________
import numpy as np
# n1 = np.arange(1,13)
n1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n2 = n1.reshape(3,4)
print(n2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 7. NumPy - Broadcasting & Element-wise Operations
# You are given the following NumPy arrays:
# a = np.array([1, 2, 3])
# b = np.array([10, 20, 30])
# Task
# Perform:
# 1.	Element-wise multiplication of a and b.
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = a*b
print(c)
# 2.	Add 5 to each element of a using broadcasting.
print(a+5,b+5)
# ________________________________________

[10 40 90]
[6 7 8] [15 25 35]


In [ ]:
# 8. Finding Maximum and Minimum Values in a NumPy Array
# Given:
# arr = np.array([[3, 7, 2], [4, 9, 6]])
# Task
# •	Find the maximum value in the entire array.
import numpy as np
arr = np.array([[3, 7, 2], [4, 9, 6]])
print(arr.max())
# •	Find the minimum value in each row.
print(arr.min())

9
2


In [ ]:
# 9. Grouping & Aggregation in Pandas
# You have the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR"],
#     "Salary": [70000, 50000, 80000, 60000, 52000]
# })
# Task
# Write a Pandas command to:
# •	Group the DataFrame by "Department" and calculate the average salary per department.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Department": ["IT", "HR", "IT", "Finance", "HR"],
     "Salary": [70000, 50000, 80000, 60000, 52000]
})
avg_salary = df.groupby('Department')['Salary'].mean()

print(avg_salary)

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [ ]:
# 10. Sorting a DataFrame
# Given the following DataFrame:
# df = pd.DataFrame({
#     "City": ["New York", "Los Angeles", "Chicago", "Houston"],
#     "Population": [8419600, 3980400, 2716000, 2328000]
# })
# Task
# •	Sort the DataFrame by Population in descending order.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "City": ["New York", "Los Angeles", "Chicago", "Houston"],
     "Population": [8419600, 3980400, 2716000, 2328000]
 })
print(df.sort_values("Population",ascending=False))


          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


In [ ]:
# 11. Multi-Indexing in Pandas
# You are given the following DataFrame:
# data = {
#     "Region": ["North", "North", "South", "South", "East", "East"],
#     "City": ["A", "B", "A", "B", "A", "B"],
#     "Sales": [200, 150, 180, 220, 300, 250]
# }
# df = pd.DataFrame(data).set_index(["Region", "City"])
# Task
# •	Retrieve the sales value for City A in the South Region using multi-indexing.
# ________________________________________
import pandas as pd
data = {
     "Region": ["North", "North", "South", "South", "East", "East"],
     "City": ["A", "B", "A", "B", "A", "B"],
     "Sales": [200, 150, 180, 220, 300, 250]
 }
df = pd.DataFrame(data).set_index(["Region", "City"])
print(df.loc[("South","A")])
# df.loc[("South","A"), "Sales"]

Sales    180
Name: (South, A), dtype: int64


In [ ]:
# 12. Creating a DataFrame from a NumPy Array
# Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].
# ________________________________________
import numpy as np
arr = np.random.randint(10,99,size=(5,4))
print(arr)
df = pd.DataFrame(arr, columns=["A","B","C","D"])
print(df)

[[57 29 12 77]
 [69 25 80 83]
 [58 56 30 94]
 [41 60 22 77]
 [97 90 42 16]]
    A   B   C   D
0  57  29  12  77
1  69  25  80  83
2  58  56  30  94
3  41  60  22  77
4  97  90  42  16


In [ ]:
# 13. Conditional Column Update
# Given the following DataFrame:
# df = pd.DataFrame({
#     "Student": ["Alice", "Bob", "Charlie", "David"],
#     "Marks": [88, 45, 76, 90],
#     "Attendance": [85, 50, 90, 60]
# })
# Task
# Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Student": ["Alice", "Bob", "Charlie", "David"],
     "Marks": [88, 45, 76, 90],
     "Attendance": [85, 50, 90, 60]
})
df.loc[df["Attendance"]<60, "Marks"]=0
print(df)

   Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60


In [8]:
# 14. Advanced Filtering
# From a CSV file "employees.csv" with columns:
# EmployeeID, Department, Salary, Experience (in years).
# Note: You should create “employees.csv” & perform the below task
# Task
# Write a Pandas query to:
# •	Select employees from "IT" or "Finance" department
# •	Having Salary > 60,000
# •	AND at least 5 years of experience
# # _______________________________________
import pandas as pd
data = {
    "EmployeeID": [1, 2, 3, 4, 5],
    "Department": ["IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [70000, 80000, 55000, 65000, 75000],
    "Experience": [6, 7, 3, 5, 8]}
df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

# Re-reading the CSV file
df = pd.read_csv('employees.csv')

# Print the original dataframe
print(df)

# Employees from "IT" or "Finance" department
print("Employees from \"IT\" or \"Finance\" department")
print(df[(df["Department"].isin(["IT", "Finance"]))])

# Employees having salary > 60,000
print("Employees Having Salary > 60,000")
print(df[df["Salary"] > 60000])

# Employees with at least 5 years of experience
print("Employees at least 5 years of experience")
print(df[df["Experience"] >= 5])

   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
2           3         HR   55000           3
3           4         IT   65000           5
4           5    Finance   75000           8
Employees from "IT" or "Finance" department
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   65000           5
4           5    Finance   75000           8
Employees Having Salary > 60,000
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   65000           5
4           5    Finance   75000           8
Employees at least 5 years of experience
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2    Finance   80000           7
3           4         IT   

In [ ]:
# 15. Grouping & Aggregation with Multiple Conditions
# Given the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
#     "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
#     "Experience": [5, 4, 7, 3, 2, 8, 6]
# })
# Task Find the average salary for each department, but only for employees with at least 5 years of experience.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
     "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
     "Experience": [5, 4, 7, 3, 2, 8, 6]
})
new_df = df.loc[df["Experience"]>=5]
print(new_df)
print(new_df.groupby("Department")["Salary"].mean())

  Department  Salary  Experience
0         IT   70000           5
2         IT   80000           7
5    Finance   72000           8
6         IT   65000           6
Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


In [ ]:
# 16. NumPy - Complex Indexing
# Create a 5x5 NumPy array with random values between 1 and 100.
# Write a NumPy command to:
# •	Extract only even numbers from the array.
# •	Extract values from the last row and last column.
# •	Replace all values greater than 50 with 0.
# ________________________________________
import numpy as np
n2 = np.random.randint(1,100, size=(5,5))
print(n2)
print("only even numbers from the array",n2[n2%2==0])
print("last row and last column", n2[-1,:],n2[:,-1])
n3=n2.copy()
n3[n3 > 50]=0
print("replace all values greater than 50 with 0", )
print(n3)

[[31 29 74 12 62]
 [80 78 47 15 41]
 [61 92 80 24 55]
 [54 76 46 26 20]
 [51 24 90 12 60]]
only even numbers from the array [74 12 62 80 78 92 80 24 54 76 46 26 20 24 90 12 60]
last row and last column [51 24 90 12 60] [62 41 55 20 60]
replace all values greater than 50 with 0
[[31 29  0 12  0]
 [ 0  0 47 15 41]
 [ 0  0  0 24  0]
 [ 0  0 46 26 20]
 [ 0 24  0 12  0]]


In [ ]:
# 17. Matrix Multiplication
# Given the two NumPy matrices:
# A = np.array([[2, 4], [6, 8]])
# B = np.array([[1, 3], [5, 7]])
# Task
# Perform matrix multiplication and output the result.
# ________________________________________
import numpy as np
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
C = np.array(A*B)
print(C)

[[ 2 12]
 [30 56]]


In [ ]:
# 18. Finding Unique & Common Elements
# You are given two NumPy arrays:
# arr1 = np.array([10, 20, 30, 40, 50, 60])
# arr2 = np.array([30, 40, 70, 80, 90])
# Task
# •	Find the elements that are common in both arrays.
# •	Find the elements that are only present in arr1 but not in arr2.
# ________________________________________
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
common_elements = np.intersect1d(arr1, arr2)
print(common_elements)
unique_in_arr1 = np.setdiff1d(arr1, arr2)
print(unique_in_arr1)

[30 40]
[10 20 50 60]


In [ ]:
# 19. Sorting & Ranking in Pandas
# You are given the following DataFrame:
# df = pd.DataFrame({
#     "Player": ["A", "B", "C", "D"],
#     "Score": [200, 450, 300, 150]
# })
# Task
# •	Sort the players by descending Score.
# •	Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers.
# ________________________________________
import pandas as pd
df = pd.DataFrame({
     "Player": ["A", "B", "C", "D"],
     "Score": [200, 450, 300, 150]
})
df=df.sort_values("Score", ascending = False)
df["Rank"]=range(1,5)
print(df.sort_index())
# print(X)

  Player  Score  Rank
0      A    200     3
1      B    450     1
2      C    300     2
3      D    150     4


In [ ]:
# 20. Optimizing Pandas Performance
# You have a large CSV file ("big_data.csv") with 1 million rows.
# Note: You should search & download a large csv file from any portal & use it to perform below tasks
# Task
# Write optimized Pandas code to:
# •	Load only specific columns: "CustomerID" and "PurchaseAmount".
# •	Load only the first 100,000 rows.
# •	Use an efficient data type for "CustomerID" to save memory.
import pandas as pd
